### ISSUE TITLE
Some templates leads to some errors on PHP

### ISSUE THREAD

**Issue by n3v1l** [WPChill/download-monitor#691]
Dear all: I have some issues with your excellent plugins, some times it just doesn't show the page with the content. 
Some of the errors:

PHP Fatal error:  Uncaught Error: Call to a member function the_download_link() on null in /var/www/html/wp-content/plugins/download-monitor/templates/content-download-button.php:12\nStack trace:\n#0 /var/www/html/wp-content/plugins/download-monitor/src/TemplateHandler.php(90): include()\n#1 /var/www/html/wp-content/plugins/download-monitor/src/Gutenberg.php(111): DLM_Template_Handler->get_template_part('content-downloa...', 'button', '', Array)\n#2 /var/www/html/wp-includes/class-wp-block.php(221): DLM_Gutenberg->render_download_button(Array, '', Object(WP_Block))\n#3 /var/www/html/wp-includes/blocks.php(799): WP_Block->render()\n#4 /var/www/html/wp-includes/blocks.php(837): render_block(Array)\n#5 /var/www/html/wp-includes/class-wp-hook.php(292): do_blocks('<!-- wp:downloa...')\n#6 /var/www/html/wp-includes/plugin.php(212): WP_Hook->apply_filters('<!-- wp:downloa...', Array)\n#7 /var/www/html/wp-includes/post-template.php(253): apply_filters('the_content', '<!-- wp:downloa...')\n#8 /var/www/html/wp-content/themes/norebro/parts/content in /var/www/html/wp-content/plugins/download-monitor/templates/content-download-button.php on line 12

HP Fatal error:  Uncaught Error: Call to a member function get_version() on null in /var/www/html/wp-content/plugins/download-monitor/templates/content-download-filename.php:12\nStack trace:\n#0 /var/www/html/wp-content/plugins/download-monitor/src/TemplateHandler.php(90): include()\n#1 /var/www/html/wp-content/plugins/download-monitor/src/Gutenberg.php(111): DLM_Template_Handler->get_template_part('content-downloa...', 'filename', '', Array)\n#2 /var/www/html/wp-includes/class-wp-block.php(221): DLM_Gutenberg->render_download_button(Array, '', Object(WP_Block))\n#3 /var/www/html/wp-includes/blocks.php(799): WP_Block->render()\n#4 /var/www/html/wp-includes/blocks.php(837): render_block(Array)\n#5 /var/www/html/wp-includes/class-wp-hook.php(292): do_blocks('<!-- wp:downloa...')\n#6 /var/www/html/wp-includes/plugin.php(212): WP_Hook->apply_filters('<!-- wp:downloa...', Array)\n#7 /var/www/html/wp-includes/post-template.php(253): apply_filters('the_content', '<!-- wp:downloa...')\n#8 /var/www/html/wp-content/themes/norebro/parts/content-p in /var/www/html/wp-content/plugins/download-monitor/templates/content-download-filename.php on line 12

Could you lead me to a way of properly solve this issue?

Thanks in advance!

**Comment by n3v1l** [comment]
PHP 7.0.33 on debian 9.13

**Comment by razvanaldea89** [comment]
Hello @n3v1l ,

Could you please some more info, like WordPress version, active plugins and theme, number of downloads you have. Seems like we can not replicate this issue. My colleague should have solved the issue with this commit https://github.com/WPChill/download-monitor/commit/c724eadfede6828e087353fc98cad113b1b29bbd , but it would be nice to see from where did this came from and prevent future errors from happening.

**Comment by bozzmedia** [comment]
I appreciate the fix is likely already identified here, just in case it helps long term my environment: php 7.0 , wp 5.8.1, thousands of downloads. Thank you!
